// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/reg.proto

package ssov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reg_Register_FullMethodName = "/auth.Reg/Register"
)

// RegClient is the client API for Reg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Empty, error)
}

type regClient struct {
	cc grpc.ClientConnInterface
}

func NewRegClient(cc grpc.ClientConnInterface) RegClient {
	return &regClient{cc}
}

func (c *regClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Reg_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegServer is the server API for Reg service.
// All implementations must embed UnimplementedRegServer
// for forward compatibility.
type RegServer interface {
	Register(context.Context, *RegisterReq) (*Empty, error)
	mustEmbedUnimplementedRegServer()
}

// UnimplementedRegServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegServer struct{}

func (UnimplementedRegServer) Register(context.Context, *RegisterReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegServer) mustEmbedUnimplementedRegServer() {}
func (UnimplementedRegServer) testEmbeddedByValue()             {}

// UnsafeRegServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegServer will
// result in compilation errors.
type UnsafeRegServer interface {
	mustEmbedUnimplementedRegServer()
}

func RegisterRegServer(s grpc.ServiceRegistrar, srv RegServer) {
	// If the following call pancis, it indicates UnimplementedRegServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reg_ServiceDesc, srv)
}

func _Reg_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reg_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Reg_ServiceDesc is the grpc.ServiceDesc for Reg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Reg",
	HandlerType: (*RegServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Reg_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/reg.proto",
}
