// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"

	"github.com/google/uuid"
)

type Admin struct {
	ID        int32
	Uid       uuid.NullUUID
	Name      sql.NullString
	CreatedAt sql.NullTime
}

type User struct {
	ID          uuid.UUID
	Username    sql.NullString
	Email       sql.NullString
	EmailStatus sql.NullBool
	PasHash     sql.NullString
	CreatedAt   sql.NullTime
}
