// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"time"

	"github.com/google/uuid"
)

type Admin struct {
	ID        int32
	Username  string
	Name      string
	CreatedAt time.Time
}

type UsersSecret struct {
	ID          uuid.UUID
	Username    string
	Email       string
	EmailStatus bool
	PassHash    string
}
